
spring:
  application:
    name: labeling-verification-service # 보이고하자하는 이름
  sleuth:
    sampler:
      probability: 1.0 # Zipkin에 트랜젝션을 어느정도의 비율로 보낼지에 대한 값이다. 기본값은 10%(0.1)이며, 1.0이면 트랜젝션을 100% 보내게 된다.
  zipkin:
    base-url: http://zipkin.istio-system.svc.cluster.local:9411/ # zipkin 경로